{
  imports = [
    ./aseprite.nix
    ./bitwig.nix
    ./davinci.nix
    ./discord.nix
    ./firefox.nix
    ./gimp.nix
    ./godot.nix
    ./inkscape.nix
    ./minecraft.nix
    ./nemo.nix
    ./obs.nix
    ./obsidian.nix
    ./spotify.nix
    ./steam.nix
    ./vlc.nix
    ./zathura.nix
  ];
}
